#!/usr/bin/env python3
"""
Generate paper Tables 1, 2, 3 from existing CSVs.
"""
import pandas as pd
import numpy as np

# ── Table 1: 5-dataset + Norman summary ──────────────────────
# Enrichment and AUROC are read from the bundled source data, not hardcoded.
# Only CLL has an AUROC artifact in the submission archive; the other four
# observational datasets have no bundled raw inputs, so their AUROC is
# reported as "not reported" rather than carried over from an earlier stage.
SRC = "figure_source_data/fig2_multidataset.csv"
NORMAN_AUROC_SRC = "scripts/table_sceptre_vs_pgaa.csv"
DATASETS = ["CLL", "Sepsis", "RA", "PBMC", "IBD"]
_src = pd.read_csv(SRC).set_index("Dataset")
_sceptre = pd.read_csv(NORMAN_AUROC_SRC)

def _enrichment(name):
    return f"{float(_src.loc[name, 'ratio']):.1f}×"

def _auroc(name):
    v = _src.loc[name, "AUROC"]
    return "not reported" if pd.isna(v) else f"{float(v):.3f}"

def _norman_auroc():
    v = _sceptre.loc[_sceptre["method"].str.contains(
        "histogram-shape", regex=False), "auroc"].iloc[0]
    return f"{float(v):.3f}"

table1 = pd.DataFrame({
    "Dataset": ["CLL 20k", "Sepsis 20k", "RA 10k", "PBMC 3k", "IBD 10k",
                "Norman 2019 CEBPE"],
    "Best PGAA statistic": ["S₁", "S₁", "S₁", "S₁", "S₁", "S₂"],
    "POS/NEG enrichment (top 100)": [_enrichment(d) for d in DATASETS] + ["n/a"],
    "AUROC (known markers)": [_auroc(d) for d in DATASETS] + [_norman_auroc()],
    "Key known targets hit": ["CD79A, CD79B, MS4A1", "TCR pathway",
                              "Cytokine pathway", "Multi-lineage",
                              "Gut immune", "ELANE rank 57/2012"],
    "S₁ ELANE-rank": ["n/a", "n/a", "n/a", "n/a", "n/a", "1452/2012"],
    "S₂ ELANE-rank": ["n/a", "n/a", "n/a", "n/a", "n/a", "57/2012 (25× improvement)"],
})
with open("scripts/table1_datasets_summary.csv", "w") as f:
    f.write("# Generated by scripts/generate_paper_tables.py from "
            f"{SRC}.\n")
    f.write("# This file is the declared source for Supplementary Table S2.\n")
    f.write("# AUROC is only reported where a bundled artifact exists: CLL 0.958\n")
    f.write("# (13-gene BCR marker set). The other four observational datasets have no\n")
    f.write("# bundled raw inputs and are marked 'not reported'.\n")
    f.write(f"# The Norman row AUROC is read from {NORMAN_AUROC_SRC}\n")
    f.write("# (PGAA-H histogram-shape row), not hardcoded.\n")
    table1.to_csv(f, index=False)

# ── Table 2: 6-perturbation S₂ calibration ───────────────────
# These six rows are a single n_bins=50 / n_perms=200 calibration run. No
# artifact for that run is in this archive: the values below and the identical
# copies in scripts/figure_s2_calibration_multitarget.py are the only record.
# The CEBPE row matches scripts/sensitivity_s2_bins.csv at n_bins=50 exactly
# (pi0 0.246, n_sig 1063), which pins the run's configuration.
# This is an UNVERIFIED_NO_ARTIFACT quantity pending the run log; do not treat
# table2_s2_calibration.csv as independent confirmation (it is a downstream
# dump of this literal).
table2 = pd.DataFrame({
    "Perturbation": ["KLF1", "CBL", "SLC4A1", "DUSP9", "CEBPE", "BAK1"],
    "n_perturbed cells": [1197, 663, 1000, 731, 566, 687],
    "n_sig (p<0.05)": [54, 173, 222, 460, 1063, 1789],
    "Storey π̂₀": [1.148, 0.715, 0.665, 0.679, 0.246, 0.104],
    "Calibration verdict": ["well-calibrated", "acceptable", "mild over-sensitive",
                            "over-sensitive", "severely over-sensitive",
                            "catastrophically over-sensitive"],
    "Recommended use": ["S₂ + S₁", "S₂ + S₁", "S₁ preferred", "S₁ only",
                        "S₂ only with caution", "S₁ only"],
})
table2.to_csv("scripts/table2_s2_calibration.csv", index=False)

# ── Table 3: Decision rule ───────────────────────────────────
table3 = pd.DataFrame({
    "Perturbation type": [
        "Mean shift (KO/OE of TF)",
        "Bimodality shift (CRISPRa, weak-effect)",
        "Mixed (multi-signal, heterogeneous population)",
        "Unknown a priori",
    ],
    "Signal type": [
        "All perturbed cells shift by α",
        "Fraction of cells shift; mean may be unchanged",
        "Mean shift + bimodality + dependencies",
        "Need to test",
    ],
    "Recommended statistic": [
        "S₁ alone (Wasserstein)",
        "S₂ alone (persistent homology) with calibration diagnostic",
        "Combined z = (z_S₁ + z_S₂)/√2",
        "S₁ first; add S₂ if S₁ finds nothing",
    ],
    "Calibration check": [
        "Negative control: GAPDH perturbation → π̂₀ > 0.5",
        "Multi-perturbation diagnostic: π̂₀ should be > 0.5 on null",
        "Both statistics should be informative before combining",
        "Always run S₂ on a null perturbation first",
    ],
    "Validated on": [
        "CLL/Sepsis/RA/PBMC/IBD (5 datasets), simulation Type A",
        "Norman 2019 CEBPE (ELANE rank 57/2012)",
        "CLL 20k TCL1A (3 BCR + 11 TCR)",
        "Norman 2019 (KLF1 π̂₀=1.15 as good null)",
    ],
})
table3.to_csv("scripts/table3_decision_rule.csv", index=False)

# Markdown formatted output
md = []
md.append("# Paper Tables\n")
md.append("\n## Table 1. PGAA performance across six datasets\n")
md.append(table1.to_markdown(index=False))
md.append("\n\n## Table 2. S₂ calibration across six Perturb-seq perturbations (Norman 2019)\n")
md.append(table2.to_markdown(index=False))
md.append("\n\n## Table 3. Decision rule for choosing S₁, S₂, or combined z\n")
md.append(table3.to_markdown(index=False))

with open("scripts/tables_paper.md", "w") as f:
    f.write("\n".join(md))

print("Saved: scripts/table1_datasets_summary.csv")
print("Saved: scripts/table2_s2_calibration.csv")
print("Saved: scripts/table3_decision_rule.csv")
print("Saved: scripts/tables_paper.md")
print("\n" + "=" * 60)
print("TABLES PREVIEW")
print("=" * 60)
for t in md:
    print(t)
